(function(){
if(typeof zeroTwoStats!=='function')return;
const oldStats=zeroTwoStats;
function akashV2Stats(){
 const source=globalThis.__zeroTwoData?.akash||{}, z=source?.settings?.akashV2||{}, ps=Array.isArray(z.purchases)?z.purchases:[], ss=Array.isArray(z.sales)?z.sales:[], cs=Array.isArray(z.collections)?z.collections:[], ex=Array.isArray(source?.expenses)?source.expenses:[];
 const purchaseRate=(date)=>{const h=(z.purchaseRates||[]).filter(x=>String(x.date)<=String(date)).sort((a,b)=>String(a.date).localeCompare(String(b.date)));return h.length?Number(h[h.length-1].rate||0):72};
 const saleable=x=>Number(x.actualQty||0)*(1+Number(x.waterPercent||0)/100);
 const saleAmt=x=>saleable(x)*Number(x.rate||0);
 const cost=x=>Number(x.actualQty||0)*purchaseRate(x.date);
 const profit=x=>saleAmt(x)-cost(x);
 const purchase=x=>Number(x.vendorMorning||0)+Number(x.vendorEvening||0);
 const paid=x=>Number(x.paid||0);
 const salesTotal=ss.reduce((s,x)=>s+saleAmt(x),0), purchaseTotal=ps.reduce((s,x)=>s+purchase(x)*purchaseRate(x.date),0), purchasePaid=ps.reduce((s,x)=>s+paid(x),0), expenseTotal=ex.reduce((s,x)=>s+Number(x.amount||0),0), collectionTotal=cs.reduce((s,x)=>s+Number(x.amount||0),0);
 const cashAvailable=ss.reduce((s,x)=>s+Number(x.cashAmount||0),0)+cs.reduce((s,x)=>s+Number(x.cashAmount||0),0)-ex.filter(x=>(x.paymentMode||'Cash')==='Cash').reduce((s,x)=>s+Number(x.amount||0),0)-purchasePaid;
 const bank=ss.reduce((s,x)=>s+Number(x.bankAmount||0),0)+cs.reduce((s,x)=>s+Number(x.bankAmount||0),0)-ex.filter(x=>(x.paymentMode||'')!=='Cash').reduce((s,x)=>s+Number(x.amount||0),0);
 const milkSold=ss.reduce((s,x)=>s+saleable(x),0);
 const profitTotal=ss.reduce((s,x)=>s+profit(x),0);
 const payable=ps.reduce((s,x)=>s+Math.max(0,purchase(x)*purchaseRate(x.date)-paid(x)),0);
 const expenseBy={};ex.forEach(x=>{const k=x.category||'Other';expenseBy[k]=(expenseBy[k]||0)+Number(x.amount||0)});
 return {salesTotal,counterTotal:salesTotal,fixedCurrent:0,fixedClosed:0,fixedFuture:0,milkSold,purchaseTotal,purchasePaid,payable,expenseTotal,collectionTotal,customerReceivable:0,cashAvailable,bankAvailable:bank,profit:profitTotal,expenseBy,dailyCount:0,sales:[],customerSales:[],milk:[],stock:[],expenses:ex,collections:[],customerPayments:[],akashV2:z};
}
window.renderZeroTwo=function(source){
 const h=oldStats('hiren'), a=akashV2Stats(), r=source==='hiren'?h:source==='akash'?a:{salesTotal:h.salesTotal+a.salesTotal,milkSold:h.milkSold+a.milkSold,purchaseTotal:h.purchaseTotal+a.purchaseTotal,purchasePaid:h.purchasePaid+a.purchasePaid,payable:h.payable+a.payable,expenseTotal:h.expenseTotal+a.expenseTotal,collectionTotal:h.collectionTotal+a.collectionTotal,customerReceivable:h.customerReceivable,cashAvailable:h.cashAvailable+a.cashAvailable,profit:h.profit+a.profit,expenseBy:Object.entries({...h.expenseBy,...a.expenseBy}).reduce((o,[k,v])=>(o[k]=(o[k]||0)+v,o),{})};
 const label=source==='hiren'?'Hiren':source==='akash'?'Akash':'All';
 const business=(name,x)=>'<div class="notice"><b>'+name+'</b><div style="display:grid;gap:5px;margin-top:8px"><div>Sales: <b>'+money(x.salesTotal)+'</b></div><div>Milk / Saleable: <b>'+Number(x.milkSold||0).toFixed(2)+' L</b></div><div>Purchase: <b>'+money(x.purchaseTotal)+'</b></div><div>Collection: <b>'+money(x.collectionTotal)+'</b></div><div>Vendor Payable: <b>'+money(x.payable)+'</b></div><div>Expenses: <b>'+money(x.expenseTotal)+'</b></div><div>Profit / Loss: <b>'+money(x.profit)+'</b></div><div>Cash Position: <b>'+money(x.cashAvailable)+'</b></div></div></div>';
 const ak=source==='akash'||source==='all'?a:null;
 const akRecent=ak?[...(ak.akashV2?.sales||[]).map(x=>({date:x.date,source:'Akash',kind:'Daily Sale',description:x.slabName,amount:(Number(x.saleableQty||0)*Number(x.rate||0))})),...(ak.akashV2?.purchases||[]).map(x=>({date:x.date,source:'Akash',kind:'Bill Purchase',description:'Main Vendor',amount:(Number(x.vendorMorning||0)+Number(x.vendorEvening||0))*Number(x.rate||0)})),...(ak.akashV2?.collections||[]).map(x=>({date:x.date,source:'Akash',kind:'Bill Collection',description:x.note||'Bulk collection',amount:Number(x.amount||0)}))]:[];
 const hr=(source==='akash'?[]:(oldStats('hiren').sales||[]).map(x=>({date:x.date,source:'Hiren',kind:'Sale',description:x.product||'Sale',amount:Number(x.amount||0)})));
 const recent=[...akRecent,...hr].sort((x,y)=>String(y.date).localeCompare(String(x.date))).slice(0,50);
 const dues=source==='akash'?[]:zeroTwoDuesRows('hiren');
 const body='<div class="sectionhead"><div><h1>All Master • '+label+' Report</h1><div class="muted">Hiren and Akash remain separate. Akash uses bulk billing and slab-based sales.</div></div><div class="toolbar"><button class="btn orange" onclick="zeroTwoReportModal()">Filter</button></div></div><div class="grid">'+metric('Total Sales',money(r.salesTotal))+metric('Milk / Saleable',Number(r.milkSold||0).toFixed(2)+' L')+metric('Purchase',money(r.purchaseTotal))+metric('Collection',money(r.collectionTotal))+metric('Vendor Payable',money(r.payable))+metric('Expenses',money(r.expenseTotal))+metric('Profit / Loss',money(r.profit))+metric('Cash Position',money(r.cashAvailable))+'</div><div class="two section"><div class="card"><h2>Business-wise Position</h2>'+business('Hiren',h)+'<div style="height:8px"></div>'+business('Akash',a)+'</div><div class="card"><h2>Profit Comparison</h2><div class="two"><div class="notice"><b>Hiren</b><br><span style="font-size:20px">'+money(h.profit)+'</span></div><div class="notice"><b>Akash</b><br><span style="font-size:20px">'+money(a.profit)+'</span></div></div><div class="section"><h3>Akash Slab Profit</h3>'+((a.akashV2?.slabs||[]).map(s=>{const rows=(a.akashV2.sales||[]).filter(x=>x.slabId===s.id),rev=rows.reduce((q,x)=>q+Number(x.saleableQty||0)*Number(x.rate||0),0),pr=rows.reduce((q,x)=>q+(Number(x.saleableQty||0)*Number(x.rate||0)-Number(x.actualQty||0)*Number((a.akashV2.purchaseRates||[]).slice().sort((p,q)=>String(p.date).localeCompare(String(q.date))).filter(p=>String(p.date)<=String(x.date)).pop()?.rate||72)),0);return '<p>'+esc(s.name)+': <b>'+money(pr)+'</b> • '+(rev?(pr/rev*100).toFixed(2):'0')+'%</p>'}).join('')||'<p class="muted">No Akash sales yet</p>')+'</div></div></div><div class="card section"><div class="sectionhead"><h2>Recent Transactions</h2><span class="muted">Business • Date • Type • Amount</span></div>'+tableRows(recent.map((x,i)=>({...x,id:String(i),_entity:'zeroTwoV2'})),[['Date',x=>fmtDate(x.date)],['Business',x=>x.source],['Type',x=>esc(x.kind)],['Description',x=>esc(x.description)],['Amount',x=>money(x.amount)]],false)+'</div><div class="card section"><div class="sectionhead"><h2>Hiren Customer Receivables</h2><span class="muted">Akash customer balances are intentionally not maintained here.</span></div>'+tableRows(dues.map((x,i)=>({...x,id:String(i),_entity:'dues'})),[['Customer',x=>esc(x.customer)],['Month',x=>x.month],['Bill',x=>money(x.bill)],['Paid',x=>money(x.paid)],['Due',x=>money(x.balance)],['Status',x=>esc(x.status)]],false)+'</div>';
 document.getElementById('root').innerHTML='<div class="app"><section class="main" style="width:100%"><header class="topbar"><div><b>Durga Dairy • Zero Two</b></div><div class="right"><span class="pill orange">Full Access</span><span class="workspace">All Data</span></div></header><main class="page">'+body+'<div class="footer">Zero Two • Read-only combined reporting • Hiren + Akash</div></main></section></div>';
};
})();